describe('Application tests', () => {
  it("Generate a simple line chart", function () {
    cy.visit('/')
    cy.contains('Line').click()
    cy.addTitle('Test')
    cy.addXlabel('V')
    cy.addYlabel('T')
    cy.addvalues("0", "1", "0")
    cy.contains('+').click()
    cy.addvalues("1", "0", "1")
    cy.contains('+').click()
    cy.addvalues("3", "5", "2")
    cy.contains('+').click()
    cy.addvalues("4", "3", "3")
    cy.contains('Generate chart').click()
    cy.get('#chart-display').should('exist')
  })

  it("Generate a simple Scatter Plot chart", function () {
    cy.visit('/')
    cy.contains('Scatter').click()
    cy.addTitle('Test2')
    cy.addXlabel('N')
    cy.addYlabel('M')
    cy.addvalues("3", "4", "0")
    cy.contains('+').click()
    cy.addvalues("2", "-1", "1")
    cy.contains('+').click()
    cy.addvalues("0", "6", "2")
    cy.contains('+').click()
    cy.addvalues("2", "1", "3")
    cy.contains('+').click()
    cy.addvalues("7", "5", "4")
    cy.contains('Generate chart').click()
    cy.get('#chart-display').should('exist')
  })

  it("Generate a simple Bar chart", function () {
    cy.visit('/')
    cy.contains('Bar').click()
    cy.addTitle('Test3')
    cy.addXlabel('X')
    cy.addYlabel('Y')
    cy.addvalues("1", "0", "0")
    cy.contains('+').click()
    cy.addvalues("3", "2", "1")
    cy.contains('+').click()
    cy.addvalues("1", "5", "2")
    cy.contains('+').click()
    cy.addvalues("-2", "-1", "3")
    cy.contains('Generate chart').click()
    cy.get('#chart-display').should('exist')
  })

  it("Generate and save a chart", function () {
    cy.visit('/')
    cy.contains('Bar').click()
    cy.addTitle('Test4')
    cy.addXlabel('V')
    cy.addYlabel('T')
    cy.addvalues("2", "8", "0")
    cy.contains('+').click()
    cy.addvalues("1", "0", "1")
    cy.contains('+').click()
    cy.addvalues("3", "5", "2")
    cy.contains('+').click()
    cy.addvalues("4", "3", "3")
    cy.contains('+').click()
    cy.addvalues("0", "5", "4")
    cy.contains('Generate chart').click()
    cy.contains('Save chart').click()
    cy.contains('Gallery').click()
    cy.get('.chart-img-container').should('exist')
    cy.get('.chart-title').should("contain", "Test4")
  })

  it("Chart data is maintained across page", function () {
    cy.visit('/')
    cy.contains('Bar').click()
    cy.addTitle('Test5')
    cy.addXlabel('V')
    cy.addYlabel('T')
    cy.addvalues("2", "8", "0")
    cy.contains('+').click()
    cy.addvalues("1", "0", "1")
    cy.contains('+').click()
    cy.addvalues("3", "5", "2")
    cy.contains('+').click()
    cy.addvalues("4", "3", "3")
    cy.contains('+').click()
    cy.addvalues("0", "5", "4")
    cy.contains('Generate chart').click()
    cy.contains('Line').click()
    cy.get('#chart-title-input').should('have.value', 'Test5')
    cy.get('#x-label-input').should('have.value', 'V')
    cy.get('#y-label-input').should('have.value', 'T')
    cy.get('.x-value-input').eq(0).should('have.value', '2')
    cy.get('.y-value-input').eq(0).should('have.value', '8')
    cy.get('.x-value-input').eq(1).should('have.value', '1')
    cy.get('.y-value-input').eq(1).should('have.value', '0')
    cy.get('.x-value-input').eq(2).should('have.value', '3')
    cy.get('.y-value-input').eq(2).should('have.value', '5')
    cy.get('.x-value-input').eq(3).should('have.value', '4')
    cy.get('.y-value-input').eq(3).should('have.value', '3')
    cy.get('.x-value-input').eq(4).should('have.value', '0')
    cy.get('.y-value-input').eq(4).should('have.value', '5')
  })

  it("Re-opening a saved chart", function () {
    cy.visit('/')
    cy.contains('Line').click()
    cy.addTitle('Test6')
    cy.addXlabel('M')
    cy.addYlabel('N')
    cy.addvalues("0", "3", "0")
    cy.contains('+').click()
    cy.addvalues("6", "2", "1")
    cy.contains('+').click()
    cy.addvalues("8", "4", "2")
    cy.contains('+').click()
    cy.addvalues("9", "5", "3")
    cy.contains('+').click()
    cy.addvalues("-1", "-3", "4")
    cy.contains('Generate chart').click()
    cy.contains('Save chart').click()
    cy.contains('Gallery').click()
    cy.contains('Test6').click()
    cy.get('#chart-display').should('exist')
    cy.get('#chart-title-input').should('have.value', 'Test6')
    cy.get('#x-label-input').should('have.value', 'M')
    cy.get('#y-label-input').should('have.value', 'N')
    cy.get('.x-value-input').eq(0).should('have.value', '0')
    cy.get('.y-value-input').eq(0).should('have.value', '3')
    cy.get('.x-value-input').eq(1).should('have.value', '6')
    cy.get('.y-value-input').eq(1).should('have.value', '2')
    cy.get('.x-value-input').eq(2).should('have.value', '8')
    cy.get('.y-value-input').eq(2).should('have.value', '4')
    cy.get('.x-value-input').eq(3).should('have.value', '9')
    cy.get('.y-value-input').eq(3).should('have.value', '5')
    cy.get('.x-value-input').eq(4).should('have.value', '-1')
    cy.get('.y-value-input').eq(4).should('have.value', '-3')
  })
})