describe('Application tests', () => {
  it("Generate a simple line chart", function () {
    cy.visit('/')
    cy.contains('Line').click()
    cy.addTitle('Test')
    cy.addXlabel('V')
    cy.addYlabel('T')
    cy.addvalues("0", "1", "0")
    cy.contains('+').click()
    cy.addvalues("1", "0", "1")
    cy.contains('+').click()
    cy.addvalues("3", "5", "2")
    cy.contains('+').click()
    cy.addvalues("4", "3", "3")
    cy.contains('Generate chart').click()
    cy.get('#chart-display').should('exist')
  })

  it("Generate a simple Scatter Plot chart", function () {
    cy.visit('/')
    cy.contains('Scatter').click()
    cy.addTitle('Test2')
    cy.addXlabel('N')
    cy.addYlabel('M')
    cy.addvalues("3", "4", "0")
    cy.contains('+').click()
    cy.addvalues("2", "-1", "1")
    cy.contains('+').click()
    cy.addvalues("0", "6", "2")
    cy.contains('+').click()
    cy.addvalues("2", "1", "3")
    cy.contains('+').click()
    cy.addvalues("7", "5", "4")
    cy.contains('Generate chart').click()
    cy.get('#chart-display').should('exist')
  })

  it("Generate a simple Bar chart", function () {
    cy.visit('/')
    cy.contains('Bar').click()
    cy.addTitle('Test3')
    cy.addXlabel('X')
    cy.addYlabel('Y')
    cy.addvalues("1", "0", "0")
    cy.contains('+').click()
    cy.addvalues("3", "2", "1")
    cy.contains('+').click()
    cy.addvalues("1", "5", "2")
    cy.contains('+').click()
    cy.addvalues("-2", "-1", "3")
    cy.contains('Generate chart').click()
    cy.get('#chart-display').should('exist')
  })
})